terminate called after throwing an instance of 'unix_error'
  what():  bind: Address already in use
Died on std::runtime_error: /usr/local/bin/../share/mahimahi/traces/trace_sine-long.up: error opening for reading
Died on std::runtime_error: /usr/local/bin/../share/mahimahi/traces/trace_sine-long.down: error opening for reading
Died on std::runtime_error: `downlink': process exited with failure status 1
Died on std::runtime_error: `mm-link /usr/local/bin/../share/mahimahi/traces/trace_sine-long.down /usr/local/bin/../share/mahimahi/traces/trace_sine-long.up --once --uplink-log=/tmp/contest_uplink_log -- sh -c ./sender $MAHIMAHI_BASE 9090': process exited with failure status 1
Died on std::runtime_error: `packetshell': process exited with failure status 1

Average capacity: 12.12 Mbits/s
Average throughput: 11.60 Mbits/s (95.7% utilization)
95th percentile per-packet queueing delay: 472 ms
95th percentile signal delay: 1468 ms
